### ISSUE TITLE
Worker can not pop last queue in PHP7.1

### ISSUE THREAD

**Issue by davidtall** [mjphaynes/php-resque#61] opened 2017-09-02 07:06 UTC
This is My config.yml file:
```
default:
     expiry_time: 604800 # Default expiry time of Redis keys
     #verbose:           # quiet=0, normal=1, verbose=2, very_verbose=3, debug=4
     #jobs:
         #queue: default  # Defalt queue to add a job to
         #delay: false    # Default delay to add to jobs false=no delay
     workers:
         queue: "*"      # Default queue to watch, *=all queues
         blocking: false  # Use Redis blocking
         interval: 1    # Worker interval (seconds)
         timeout: 60     # Job timeout (seconds)
         memory: 128     # Max worker memory
         #pid: 20088     # Max worker memory
```
First ,I push 100 jobs into redis by random queue:
```
for($i=0;$i<100;$i++){
       Resque::push('Open\\Job\\TestJob', array(), "shop" . mt_rand(1, 100));
}
```
Then ,I start one worker by running command `bin/resque worker:start -vvv`
the worker finish jobs,and the main process into `Worker: waiting for job on * with interval 1 second` status.
But I see the redis ,There are still three jobs not processed,They belong to the last queue named "resque:queue:shop99".
then I debug the source code
https://github.com/mjphaynes/php-resque/blob/8ec37dbcde8fbf4088efd2385cc015f765ec16da/src/Resque/Queue.php#L127-L145

I insert debug code `print_r($queue.PHP_EOL)` into L140 and restart worker.
```
foreach ($queues as $queue) {
    print_r($queue.PHP_EOL);
    if ($payload = $this->redis->lpop($queue)) {
           break;
    }
}
```
It can not print queue "queue:shop99",but print queue "queue:shop98" twice.
I think the problem is because line 131 use `&`
https://github.com/mjphaynes/php-resque/blob/8ec37dbcde8fbf4088efd2385cc015f765ec16da/src/Resque/Queue.php#L131
So I modify `$queue` into `$q` in line 139 like that:
https://github.com/mjphaynes/php-resque/blob/8ec37dbcde8fbf4088efd2385cc015f765ec16da/src/Resque/Queue.php#L139
```
foreach ($queues as $q) {
        print_r($q.PHP_EOL);
        if ($payload = $this->redis->lpop($q)) {
               $queue = $q;
               break;
         }
}
```
Restart the worker ,It can print "queue:shop99" and perform last three jobs successfully.
So I'm sure that It's a bug beacause PHP7 foreach feature ,see http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.array-order

I think the better way to fix this bug is replace Line 131 with 
```
        foreach ($queues as $key=>$queue) {
            $queues[$key] = self::redisKey($queue);
        }
```
instead using `&$queue` @francislavoie @mjphaynes @xelan

**Comment by francislavoie** [comment] 2017-09-02 12:10
By the way, I'm pretty sure that using blocking: true is faster/more efficient in every situation. It uses BLPOP instead of LPOP which means it will block waiting for redis to give back a result instead of doing a sleep. That means less CPU overhead (I think) and the job can get popped from the list immediately if something gets added versus waiting until after the sleep is done to check again. You can probably also increase your interval as well to something much higher.

Awesome job debugging this problem! If I'm reading it correctly it looks like the next foreach tries to assign to $queue which means it overwrites the last queue in the list with the first one in the list, or something like that.

**Comment by davidtall** [comment] 2017-09-03 03:34
I want it to handle the job in parallel, not one by one. I have changed `sleep($this->interval)` into` usleep($this->interval * 1000000);` and set var interval =0.001,so I use blocking: false

**Comment by davidtall** [comment] 2017-09-03 03:36
Do you think it is necessary to change `sleep($this->interval)` into `usleep($this->interval * 1000000);`?

**Comment by francislavoie** [comment] 2017-09-03 03:41
I think you should use `blocking: true` and just run multiple workers. The parallelism will come from having multiple workers. I don't think you'll ever get parallelism from a single worker even if you make the interval very low, because the worker expects exactly one job to run at a time by design, so it can report back the result of the child job. If it had to manage multiple running jobs at the same time, it would complicate things heavily. If you turn on blocking, then as soon as a new job comes in, redis will serve it to the waiting workers instantly, without the worker needing to finish it's `sleep` cycle first. You end up having jobs running earlier with blocking turned on.

**Comment by davidtall** [comment] 2017-09-03 05:02
Oh,I know your mean.Because redis can only run command one by one (or step by step?),worker can't pop the job at the same time from redis . I should use `blocking: true` instead of using sleep.Thanks

**Comment by xelan** [comment] 2017-09-17 12:00
Bug reproducable on Debian 9.1, PHP `7.1.9-1+0~20170902060745.8+stretch~1.gbpebe5d6`

Apparently, this bug only happens if the blocking mode is disabled.

**Closed** 2017-09-17 12:09 UTC
Labels: Bug
